import type { Metadata } from "next";

import "./globals.css";

export const metadata: Metadata = {
  title: "Pink Portfolio",
  description: "Generated by Usman",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        
      >
        {children}
      </body>
    </html>
  );
}
